from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_report(
        filename,
        ats_score,
        match_score,
        skills):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    title = Paragraph(
        "AI Resume Analysis Report",
        styles['Title']
    )

    content.append(title)

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            f"<b>ATS Score:</b> {ats_score}%",
            styles['Normal']
        )
    )

    content.append(
        Paragraph(
            f"<b>Job Match Score:</b> {match_score}%",
            styles['Normal']
        )
    )

    content.append(Spacer(1, 10))

    skills_text = ", ".join(skills)

    content.append(
        Paragraph(
            f"<b>Detected Skills:</b> {skills_text}",
            styles['Normal']
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by AI Resume Analyzer",
            styles['Italic']
        )
    )

    pdf.build(content)

    return filename